### ISSUE TITLE
Container exits immediately after running

### ISSUE THREAD

**Issue by sanderobdeijn** [haysclark/docker-adlmflexnetserver#10]
I'm trying to run this container with the command in the readme.
I did add an backlslash after the image name.
```
docker run -d --mac-address=<license-mac-address> \
-h <license-hostname> \
-v <local-license-path>:/var/flexlm/adsk_server.lic:ro \
-p 2080:2080 -p 27000-27009:27000-27009 \
haysclark/adlmflexnetserver \
-c /var/flexlm/adsk_server.lic
```
This runs but exits immediately. Isn't the -z option supposed to prevent this.
I don't seem to get any logs or errors do you have any idea what is happening here?

**Comment by haysclark** [comment]
@sanderobdeijn Sorry for not getting back to you sooner Sander. You likely need to add a `-z` flag, which I mention in the [Readme under Usage](https://github.com/haysclark/docker-adlmflexnetserver#usage). I'll try to tweak the docs so that this is more clear.

**Comment by haysclark** [comment]
@sanderobdeijn Sorry that I am getting back to you so late. Unfortunately, I do not see anything wrong with the command you sent me. ☹️ Just to validate that all is well, I deleted the image locally today and pulled the _latest_ version and restarted the command and everything is working as expected.

### Some stabs in the dark:
- If you do not see any logs from `docker logs <container_name>` then possibly you are running into issues with Docker itself? Maybe try adding `--debug` to the docker command?
- Check that the needed ports are free on your Host.
- Check the various permissions for the files Docker is trying to access.
- Depending on your setup and user permissions, you might want to try running the command with 'sudo'. It shouldn't be needed but might help with debugging the issue.
- If using Docker Desktop locally: 
  - Are the 'File Sharing' options setup correct?
  - Do you have enough CPU and Memory?

Let me know if any of these ideas help and I can add them to the [Troubleshooting section](https://github.com/haysclark/docker-adlmflexnetserver#troubleshooting). If you are still stuck, please provide the following info and I will see if I can try to help.
- Host OS
- Docker version

### Additional example (based on the command I use on my production server):
> In this example, the mac address I am using is faking is `1F2E3D4C5B6A`, which is also the formatting found in the _mayaserver.lic_ files. In the command Docker is expecting the address to be formatted as follows: `1F:2E:3D:4C:5B:6A`. Docker **will** throw an error is there is an issue. eg `docker: 1F2E3D4C5B6A is not a valid mac address.`

```bash
# start a FlexLM container
docker run -d --name flexlm \
           --restart=always \
           -p 2080:2080 -p 27000-27009:27000-27009 \
           --mac-address=1F:2E:3D:4C:5B:6A \
           -h mayaserver.mydomain.com \
           -v /mnt/mynetworkfolder/mayaserver.mydomain.lic:/var/flexlm/mayaserver.lic:ro \
           haysclark/adlmflexnetserver \
           -c /var/flexlm/mayaserver.lic
```

**Comment by haysclark** [comment]
Closing due to issue inactivity. Feel free to re-open if still blocked, providing more information.
