### ISSUE TITLE
Multiple license servers

### ISSUE THREAD

**Issue by mcmichels** [haysclark/docker-adlmflexnetserver#4]
I am thinking about using your image to deploy several autodesk license server.
Why is it necessary to expose all Ports (27000 - 27009) to one container? Normally the server will just need one of these ports. This would allow, that i bind different containers to different public ports and then i can run several license servers on one host. Is this possible?

**Comment by haysclark** [comment]
The Docker container I authored is wrapping _lmgrd_ as that is the most commonly utilized tool in the LM suite. The container uses the standard incoming port for _lmgrd_ and FlexLM. 

See: [Internet Assigned Numbers Authority (IANA)](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=flex)

| Service Name | Port Number / Transport Protocol | Description                         |
| -------------- |:---------------------------------:| --------------------------:|
| flex-lm             | 27000-27009                                 | FLEX LM (1-10)                   |
| autodesk-nlm  | 2080/tcp                                        | Autodesk NLM (FLEXlm)    |
| autodesk-nlm  | 2080/udp                                       | Autodesk NLM (FLEXlm)    |

FlexLM uses a range to support as many clients as possible from a single server. Keep in mind that it's a [dinosaur](https://en.wikipedia.org/wiki/FlexNet_Publisher) of a technology from the late 1980's. For your situation, you might be able to specify the ports you want to use in your license files, then just map those ports when you call the docker container.  

> Check out this [post](http://upandready.typepad.com/up_and_ready/2011/05/flexnet-dont-like-27000-or-2080-port-numbers-change-them.html) for details on how to accomplish this. Make sure to check out the comments to see some feedback from Autodesk specific to ports and port ranges.

If that does not work for you then you might have to consider ['Migrating to lmadmin'](https://www.3ds.com/fileadmin/PRODUCTS-SERVICES/SIMULIA/RESOURCES/FLEXlm-License-Administration11.6.1.pdf) which I know little about. Utilizing _lmadmin_ would require forking my container or just making your own, but I think the license file option above will make that unnecessary.
