### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by mcmichels** [haysclark/docker-adlmflexnetserver#5]
I started my container with following command:
docker run -d --mac-address="00:19:99:XX:XX:XX" \
-h hostname \
--name autodesktest \
-v /opt/autodesk-testserver/license.lic:/var/flexlm/adsk_server.lic:ro \
-p 2080:2080 -p 27000-27009:27000-27009 \
haysclark/adlmflexnetserver \
-c /var/flexlm/adsk_server.lic

but when i start a program and a license is obtained from this server i cannot see anything in the logs. Also there is no logging when i borrow licenses.

**Comment by haysclark** [comment]
Sorry for the delay! Are you seeing absolutely no logging when you run Dockers logs command? Or are you just missing the ```IN``` and ```OUT``` messages? The container does not store any log files internally anymore, instead, all of the STDOUT output is collected by Docker.

Just to cover the basics, when you run the docker logs command, ```docker logs [CONTAINER_ID]```, you should see something like this:

```
➜  ~ docker logs flexlm 
                                                                    
                                ##        .                         
                          ## ## ##       ==                         
                       ## ## ## ##      ===                         
                   /""""""""""""""""\\\___/ ===                     
              ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~                
                   \\______ o          __/                         
                     \\    \\        __/                          
                      \\____\\______/                             
                                                                    
  _   _           __  __ _    _      _    ___ _    _____  ___       
 | | | |_ _  ___ / _|/ _(_)__(_)__ _| |  | __| |  | __\ \/ / |_ __  
 | |_| | ' \/ _ \  _|  _| / _| / _` | |  | _|| |__| _| >  <| | '  \ 
  \___/|_||_\___/_| |_| |_\__|_\__,_|_|  |_| |____|___/_/\_\_|_|_|_|
    _  _     _                  _      ___                          
   | \| |___| |___ __ _____ _ _| |__  / __| ___ _ ___ _____ _ _     
   | .` / -_)  _\ V  V / _ \ '_| / /  \__ \/ -_) '_\ V / -_) '_|    
   |_|\_\___|\__|\_/\_/\___/_| |_\_\  |___/\___|_|  \_/\___|_|      
                                                                    
---------------------------------------------------------------------------
lmutil - Copyright (c) 1989-2015 Flexera Software LLC. All Rights Reserved.
The FlexNet host ID of this machine is "[YOUR_MAC_ADDRESS]"
---------------------------------------------------------------------------

 5:39:13 (lmgrd) -----------------------------------------------
 5:39:13 (lmgrd)   Please Note:
 5:39:13 (lmgrd) 
 5:39:13 (lmgrd)   This log is intended for debug purposes only.
 5:39:13 (lmgrd)   In order to capture accurate license
```

Hopefully, this is working. If not, double check that you are running the latest version of the container: ```docker pull haysclark/adlmflexnetserver:latest```

Moving on to the expected 'license borrowing' output, this is what I see on my own server.  I'm running ```docker logs -f [CONTAINER_ID]``` with the _follow_ flag to watch what is happening in real-time. When I start Maya this is the output:
```
 5:09:32 (adskflex) OUT: "12345MAYA_2014_0F" hays@MacBook-Pro
```

When I close Maya I see the following output:
```  
 5:10:06 (adskflex) IN: "12345MAYA_2014_0F" hays@MacBook-Pro 
```

Finally, your docker command looks good, just double check that the `hostname` and 'mac-address' matches your license files.

My _server license_ starts like this:
```
SERVER mayaserver.my-domain.com 012345abcdef
USE_SERVER
VENDOR adskflex port=2080
...
```

My _client license_, ```maya.lic``` starts like this:
```
SERVER mayaserver.my-domain.com 0
USE_SERVER
```

Again, sorry for the delay.

**Comment by haysclark** [comment]
Will re-open if there is an issue.
