### ISSUE TITLE
MotionBuilder in Docker

### ISSUE THREAD

**Issue by alexisrolland** [haysclark/docker-adlmflexnetserver#6]
Hello,
Slightly unrelated question but I thought I would ask since you seem to have experience with Autodesk softwares. Do you know if it is possible to run MotionBuilder or Maya in Docker containers?
Thank you

**Comment by haysclark** [comment]
Sorry for not seeing this earlier.

"Yes" for _Maya_, see: https://github.com/mottosso/docker-maya

"Not sure" for _MotionBuilder_. Nothing comes up on Google, which makes me a little suspicious. I would figure someone might have done it. Maybe @mottosso's Maya work can point you in the right direction?

**Comment by alexisrolland** [comment]
Thank you and no problem for the delay. I’ll check that out!

**Comment by haysclark** [comment]
Good luck! Closing issue.
